<?php

namespace App\Shared\Exception;

/**
 * Единый список всех уникальных кодов ошибок в приложении.
 * Используется в exception классах, например UnprocessableEntityException.
 */
enum ErrorCode: string
{
    // Общие
    case S_INTERNAL_SERVER_ERROR = 'S_INTERNAL_SERVER_ERROR';
    case S_BAD_REQUEST = 'S_BAD_REQUEST';
    case S_DEFAULT_UNPROCESSABLE_ENTITY = 'S_DEFAULT_UNPROCESSABLE_ENTITY';
    case S_NOT_FOUND = 'S_NOT_FOUND';
    case S_ACCESS_DENIED = 'S_ACCESS_DENIED';
    case S_SEND_FAILED = 'S_SEND_FAILED';
    case S_ROUTE_NOT_FOUND = 'S_ROUTE_NOT_FOUND';

    // Быстрая регистрация
    case B_USER_NOT_FOUND = 'USER_NOT_FOUND';
    case B_USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS';
    case B_EMAIL_VERIFICATION_ATTEMPTS_EXCEEDED = 'B_EMAIL_VERIFICATION_ATTEMPTS_EXCEEDED';
    case B_ROLE_UNAVAILABLE_IN_COUNTRY = 'B_ROLE_UNAVAILABLE_IN_COUNTRY';
    case B_RESEND_INTERVAL_NOT_EXPIRED = 'B_RESEND_INTERVAL_NOT_EXPIRED';
    case B_MAX_RESEND_ATTEMPTS_EXCEEDED = 'B_MAX_RESEND_ATTEMPTS_EXCEEDED';
    case B_TOO_MANY_REQUESTS = 'Verification_B_TOO_MANY_REQUESTS';
    case B_MAIL_REGISTRATION_ALREADY_PENDING = 'B_MAIL_REGISTRATION_ALREADY_PENDING';
    case B_PERSONAL_DATA_CONSENT_REQUIRED = 'B_PERSONAL_DATA_CONSENT_REQUIRED';
    case B_MARKETING_CONSENT_REQUIRED = 'B_MARKETING_CONSENT_REQUIRED';
    case B_MARKETING_VERSION_MISSING = 'B_MARKETING_VERSION_MISSING';
    case B_FIELD_REQUIRED = 'B_FIELD_REQUIRED';
    case B_FIELD_MUST_BE_STRING = 'B_FIELD_MUST_BE_STRING';
    case B_FIELD_MUST_BE_STRING_OR_NULL = 'B_FIELD_MUST_BE_STRING_OR_NULL';
    case B_FIELD_MUST_BE_BOOL = 'B_FIELD_MUST_BE_BOOL';
    case B_EMAIL_INVALID = 'B_EMAIL_INVALID';

    // Проверка ввода кода почты
    case B_OTP_REQUEST_ID_REQUIRED = 'B_OTP_REQUEST_ID_REQUIRED';
    case B_OTP_CODE_REQUIRED = 'B_OTP_CODE_REQUIRED';
    case B_OTP_REQUEST_ID_INVALID = 'B_OTP_REQUEST_ID_INVALID';
    case B_OTP_CODE_INVALID = 'B_OTP_CODE_INVALID';
    case B_REG_NOT_FOUND = 'B_REG_NOT_FOUND';
    case B_REG_EXPIRED = 'B_REG_EXPIRED';
    case B_OTP_NOT_FOUND = 'B_OTP_NOT_FOUND';
    case B_OTP_ATTEMPTS_EXCEEDED = 'B_OTP_ATTEMPTS_EXCEEDED';

    // Справочники
    case D_NOT_FOUND_DICTIONARY_COUNTRIES = 'D_NOT_FOUND_DICTIONARY_COUNTRIES';
    case D_ROLE_NOT_FOUND = 'D_ROLE_NOT_FOUND';
    case D_COUNTRY_NOT_FOUND = 'D_COUNTRY_NOT_FOUND';
    case D_INTEGRATION_ERROR = 'D_INTEGRATION_ERROR';

    // Валидация
    case B_VALIDATION_FAILED = 'Verification_D_VALIDATION_FAILED';
    case B_COUNTRY_NOT_FOUND = 'Verification_D_COUNTRY_NOT_FOUND';
    case B_ROLE_NOT_FOUND = 'Verification_D_ROLE_NOT_FOUND';
    case B_CHANNEL_NOT_FOUND = 'Verification_CHANNEL_NOT_FOUND';
    case B_PHONE_INVALID = 'Verification_PHONE_INVALID';
    case B_COUNTRY_INVALID_FORMAT = 'Verification_COUNTRY_INVALID_FORMAT';
    case B_CHANNEL_INVALID_FORMAT = 'Verification_CHANNEL_INVALID_FORMAT';
    case B_EMAIL_MISMATCH = 'Verification_CHANNEL_EMAIL_MISMATCH';
    case VERIFICATION_EMAIL_PROCESS_ALREADY_STARTED = 'VERIFICATION_EMAIL_PROCESS_ALREADY_STARTED';
    case B_SMS_VERIFICATION_CODE_MISMATCH = 'B_SMS_VERIFICATION_CODE_MISMATCH';

    // Company Registration
    case VALIDATION_ERROR = 'VALIDATION_ERROR';
    case NOT_FOUND = 'NOT_FOUND';
    case DUPLICATE = 'DUPLICATE';
    case INVALID_STEP = 'INVALID_STEP';
    case INTERNAL_ERROR = 'INTERNAL_ERROR';
    case VERIFICATION_AUTH_INVALID_TOKEN = 'VERIFICATION_AUTH_INVALID_TOKEN';
    case VERIFICATION_UNAUTHORIZED = 'VERIFICATION_UNAUTHORIZED';
}
