#framework:
#    messenger:
#        transports:
#            kafka:
#                dsn: "ed+kafka://%env(KAFKA_BOOTSTRAP_SERVERS)%?security_protocol=%env(KAFKA_SECURITY_PROTOCOL)%&sasl_mechanisms=%env(KAFKA_SASL_MECHANISM)%&sasl.username=%env(KAFKA_SASL_USERNAME)%&sasl.password=%env(KAFKA_SASL_PASSWORD)%"
#
#                options:
#                    topics: ['verification_events']
#                serializer: messenger.transport.symfony_serializer
#
#        routing:
#            'App\Application\Registration\QuickSignup\DTO\QuickSignupKafkaMessage': kafka
