<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260609122759 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'verification_users table (country_id fixed to CHAR(2))';
    }

    public function up(Schema $schema): void
    {
        $schemaName = $_ENV['DB_SCHEMA'] ?? 'public';
        $table = "\"{$schemaName}\".\"verification_users\"";

        $this->addSql("
            CREATE TABLE {$table}
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                request_id UUID NOT NULL,

                legal_entity VARCHAR(100) NOT NULL,

                company_id VARCHAR(50),
                role_id VARCHAR(50) NOT NULL,

                country_id character(2) COLLATE pg_catalog.\"default\" NOT NULL,

                email VARCHAR(255) NOT NULL,

                last_name VARCHAR(100) NOT NULL,
                first_name VARCHAR(100) NOT NULL,
                patronymic VARCHAR(100),

                phone_number VARCHAR(20) NOT NULL,

                verification_channel_id character varying(64) COLLATE \"default\" NOT NULL,

                verification_code VARCHAR(10),

                verification_attempts INTEGER NOT NULL DEFAULT 0,

                is_verified BOOLEAN NOT NULL DEFAULT FALSE,

                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
                updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),

                CONSTRAINT verification_users_pkey PRIMARY KEY (id),

                CONSTRAINT uq_verification_users_request_id UNIQUE (request_id)
            )
        ");

        $this->addSql("
            COMMENT ON TABLE {$table}
            IS 'Верифицированные пользователи (SMS/email verification flow)'
        ");

        $this->addSql("COMMENT ON COLUMN {$table}.request_id IS 'UUID запроса регистрации'");
        $this->addSql("COMMENT ON COLUMN {$table}.legal_entity IS 'ИНН / идентификатор юр.лица'");
        $this->addSql("COMMENT ON COLUMN {$table}.company_id IS 'Идентификатор компании'");
        $this->addSql("COMMENT ON COLUMN {$table}.role_id IS 'Код роли пользователя'");
        $this->addSql("COMMENT ON COLUMN {$table}.country_id IS 'ISO 3166-1 alpha-2 код страны'");
        $this->addSql("COMMENT ON COLUMN {$table}.email IS 'Email пользователя'");
        $this->addSql("COMMENT ON COLUMN {$table}.last_name IS 'Фамилия'");
        $this->addSql("COMMENT ON COLUMN {$table}.first_name IS 'Имя'");
        $this->addSql("COMMENT ON COLUMN {$table}.patronymic IS 'Отчество'");
        $this->addSql("COMMENT ON COLUMN {$table}.phone_number IS 'Телефон'");
        $this->addSql("COMMENT ON COLUMN {$table}.verification_channel_id IS 'Канал отправки кода'");
        $this->addSql("COMMENT ON COLUMN {$table}.verification_code IS 'Код подтверждения'");
        $this->addSql("COMMENT ON COLUMN {$table}.verification_attempts IS 'Попытки подтверждения'");
        $this->addSql("COMMENT ON COLUMN {$table}.is_verified IS 'Флаг успешной верификации'");
        $this->addSql("COMMENT ON COLUMN {$table}.created_at IS 'Дата создания'");
        $this->addSql("COMMENT ON COLUMN {$table}.updated_at IS 'Дата обновления'");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_verification_users_company_id
                ON {$table} (company_id)
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_verification_users_role_id
                ON {$table} (role_id)
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_verification_users_country_id
                ON {$table} (country_id)
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_verification_users_phone
                ON {$table} (phone_number)
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_verification_users_email
                ON {$table} (email)
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_verification_users_verified
                ON {$table} (is_verified)
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_verification_users_channel_id
                ON {$table} (verification_channel_id)
        ");
    }

    public function down(Schema $schema): void
    {
        $schemaName = $_ENV['DB_SCHEMA'] ?? 'public';
        $table = "\"{$schemaName}\".\"verification_users\"";

        $this->addSql("DROP TABLE IF EXISTS {$table}");
    }
}
