<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260330210426 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создана таблица регистрации обращений проверок почты signup_requests без foreign keys';
    }

    public function up(Schema $schema): void
    {
        $schemaName = $_ENV['DB_SCHEMA'] ?? 'public';

        $signupTable = "\"{$schemaName}\".\"signup_requests\"";

        $this->addSql("
            CREATE TABLE {$signupTable}
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                request_id UUID NOT NULL,
                role_code VARCHAR(50) NOT NULL,
                country_alpha2 CHAR(2) NOT NULL,
                email TEXT NOT NULL,

                date_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                resend_attempts INTEGER NOT NULL DEFAULT 0,
                verification_code VARCHAR(10) NOT NULL DEFAULT '',
                verification_attempts INTEGER NOT NULL DEFAULT 0,
                is_verified BOOLEAN NOT NULL DEFAULT FALSE,

                ip_address VARCHAR(45),

                accept_terms BOOLEAN NOT NULL,
                accept_marketing BOOLEAN,
                accept_marketing_ver VARCHAR(20),

                url_page_checkout TEXT,
                user_agent TEXT,

                status VARCHAR(64) NOT NULL,

                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),

                CONSTRAINT signup_requests_pkey PRIMARY KEY (id),
                CONSTRAINT uq_request_id UNIQUE (request_id)
            )
        ");

        $this->addSql("
            COMMENT ON COLUMN {$signupTable}.request_id
            IS 'UUID v4 generated in Symfony'
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_signup_status
            ON {$signupTable} (status)
        ");
    }

    public function down(Schema $schema): void
    {
        $schemaName = $_ENV['DB_SCHEMA'] ?? 'public';
        $signupTable = "\"{$schemaName}\".\"signup_requests\"";

        $this->addSql("
            DROP TABLE IF EXISTS {$signupTable}
        ");
    }
}
