parameters:
    dictionary_service_url: '%env(DICTIONARY_SERVICE_URL)%'
    app.timezone: '%env(APP_TIMEZONE)%'
    db_schema: '%env(DB_SCHEMA)%'
    app.name: '%env(APP_NAME)%'
    app.version: '%env(APP_VERSION)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Infrastructure\Dictionary\HttpDictionaryProvider:
        arguments:
            $baseUrl: '%dictionary_service_url%'

    App\Infrastructure\Application\ApplicationInfo:
        arguments:
            $name: '%app.name%'
            $version: '%app.version%'

    App\Shared\Time\ClockInterface:
        alias: App\Shared\Time\SystemClock

    App\Shared\Time\SystemClock:
        arguments:
            $timezone: '%app.timezone%'

    App\Infrastructure\DB\SchemaSqlHelper:
        arguments:
            $schema: '%db_schema%'
